Check for executable tool in fo to dvi/pdf script
git-svn-id: http://svn.fedorahosted.org/svn/xmlto@36 eb1b79c1-ba03-4820-82f3-b60cf523859b

diff --git a/format/fo/dvi b/format/fo/dvi
--- a/format/fo/dvi
+++ b/format/fo/dvi
@@ -6,6 +6,11 @@ post-process)
   then
     echo >&2 "Post-process XSL-FO to DVI"
   fi
+  if [ ! -x $XMLTEX_PATH ]
+  then
+    echo >&2 "Can't process, xmltex tool not found at $XMLTEX_PATH."
+    exit 3
+  fi
   # Work around stupid tetex bug with '_' in filenames
   # Also work around stupid tetex limitation with long lines (bug #101055)
   sed -e "s,/>,\n/>,g" "$XSLT_PROCESSED" >tmp.fo
diff --git a/format/fo/pdf b/format/fo/pdf
--- a/format/fo/pdf
+++ b/format/fo/pdf
@@ -8,6 +8,11 @@ DEFAULT|DBLATEX)
 	  then
 	    echo >&2 "Post-process XSL-FO to PDF"
 	  fi
+	  if [ ! -x $PDFXMLTEX_PATH ]
+	  then
+	    echo >&2 "Can't process, pdfxmltex tool not found at $PDFXMLTEX_PATH."
+	    exit 3
+	  fi
 	  # Work around stupid tetex bug with '_' in filenames
 	  # Also work around stupid tetex limitation with long lines (bug #101055)
 	  sed -e "s,/>,\n/>,g" "$XSLT_PROCESSED" >tmp.fo
